# Generated by Django 3.1.2 on 2021-01-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0003_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default=0, upload_to='imageforgames/'),
        ),
    ]
