# Generated by Django 3.1.2 on 2021-01-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0006_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='waiting_list',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
