# Generated by Django 3.1.2 on 2021-01-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0007_auto_20210117_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='waiting_list',
            field=models.IntegerField(default=0),
        ),
    ]
