# Generated by Django 3.1.2 on 2021-01-19 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0009_matchpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='game',
        ),
        migrations.AddField(
            model_name='matchpt',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gamers.game'),
        ),
    ]
