# Generated by Django 3.1.2 on 2021-01-19 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0014_remove_matchpt_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchpt',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gamers.game'),
        ),
    ]
